name: user_repository
description: A new Flutter package project.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
